### PR TITLE
fix:  Improve speed of kdtree grouping by pointops

### PR DESCRIPTION
**Pull request by small-zeng**
Thanks for your nice work.

When the point count is too large, CPU loop querying for the nearest points becomes too slow. It is recommended to switch to point operations querying

### CODE REVIEW

**Comment by yhyang-myron** [comment]
Thank you for interest in our work and pull request! I notice that the function _get_matching_indices_ is missing a return.

**Comment by small-zeng** [comment]
> Thank you for interest in our work and pull request! I notice that the function _get_matching_indices_ is missing a return.

Soory，I have added it

**Comment by yhyang-myron** [comment]
I tried it on scene0000_00, but met an IndexError: at [here](https://github.com/small-zeng/SegmentAnything3D/blob/f923bb9d61d799033aa7d270e57528f4e345ec1c/sam3d.py#L140), index 3007 is out of bounds for axis 0 with size 3005.

**Comment by small-zeng** [comment]
> I tried it on scene0000_00, but met an IndexError: at [here](https://github.com/small-zeng/SegmentAnything3D/blob/f923bb9d61d799033aa7d270e57528f4e345ec1c/sam3d.py#L140), index 3007 is out of bounds for axis 0 with size 3005.

I check it, and the problem is 186 line in sam3d.py, it is modified.

image

**Comment by small-zeng** [comment]
> I tried it on scene0000_00, but met an IndexError: at [here](https://github.com/small-zeng/SegmentAnything3D/blob/f923bb9d61d799033aa7d270e57528f4e345ec1c/sam3d.py#L140), index 3007 is out of bounds for axis 0 with size 3005.
The code is copied from another project, so something can be missing

**Comment by small-zeng** [comment]
> I tried it on scene0000_00, but met an IndexError: at [here](https://github.com/small-zeng/SegmentAnything3D/blob/f923bb9d61d799033aa7d270e57528f4e345ec1c/sam3d.py#L140), index 3007 is out of bounds for axis 0 with size 3005.

Thank you, I try this modified code, there is no error.
image

**Comment by yhyang-myron** [comment]
Thank you !

**Pull request merged**
